### PR TITLE
Added tests for enterprise beans

### PR DESCRIPTION
**Pull request by arjantijms**
Signed-off-by: arjantijms <arjan.tijms@gmail.com>

### CODE REVIEW

**Comment by janbeernink** [comment]
Had a quick look at this and it looks good, but for some reason the Liberty tests are failing at the moment. Do you happen to know why these are failing?

**Comment by arjantijms** [comment]
> Had a quick look at this and it looks good, but for some reason the Liberty tests are failing at the moment. Do you happen to know why these are failing?

I think it's a coincidence / GitHub fluke:

"EnterpriseTest » Deployment Timeout while waiting for "ac902e71-b885-42fa-9f24..."

**Comment by janbeernink** [comment]
Hmm, that's odd. I've triggered the tests again, let's see what happens.

**Comment by arjantijms** [comment]
> Hmm, that's odd. I've triggered the tests again, let's see what happens.

Maybe something Arquillian related, or maybe Liberty wants some special EJB configuration. Although it should not be the case, EJB does originate from a time where it was seen as fancy to have product specific configuration. The concept of portability wasn't yet such as we think about it today.

**Comment by arjantijms** [comment]
Let's abandon the tests then. I think Liberty should be able to run EJB, but somehow it doesn't. @Emily-Jiang any idea?

**Pull request closed without merging**
