### PR TITLE
Interceptor for PooledScoped beans

### PR DESCRIPTION
**Pull request by OndrejM**
I see that PooledContext uses Javassist to wrap pooled beans and release them after method is called. I tried and idea to combine PooledContext together with an Interceptor, which does the release work instead of Javassist. The tricky part is communication between PooledContext and interceptor - I used thread local variable, but I still have some issues with nested calls to pooled beans in the same thread. But I think that can be resolved easily with putting nested beans on stack instead of using only single value in thread local.

I removed Javassist dependency, the interceptor is bound automatically to beans marked with Pooled annotation (does not support producers yet).

Do you whink this idea is viable? I also wrote some tests to demonstrate, but for some reasons I could not put the test code inside the same project (CDI extension was not loaded). If you think this approach makes sense, I my elaborate more.

### CODE REVIEW

**Comment by janbeernink** [comment]
Hi Ondrej, 

Many thanks for your pull request. I agree that the dependency on Javassist is not entirely an optimal solution. We did actually look at your solution where a call to PooledContext.get() would cause the bean to be allocated and the interceptor would release it again. We decided against this as it is possible to call PooledContext.get() directly through the BeanManager from application code. While it is unlikely that this would happen, this would cause instances to "leak" and eventually cause thread starvation. This is one of the reasons we decided to go with the Javassist approach instead of using interceptors.

With regard to recursive calls, we experimented with introducing a layered [PooledScope](https://github.com/omnifaces/cdi-ejb/blob/ca01f08e4e7b393077c8d0906bca6fadba321fa9/src/main/java/org/omnifaces/cdi/pooled/PooledScope.java) which held a reference to the PoolKey of the bean allocated in the current layer. Each method call to an @Pooled bean would cause a new layer to be created. This would allow for recursive calls to @Pooled beans.

Once again many thanks for your interest. I will keep this pull request open for now as I think the approach certainly has merit. If we can make it waterproof somehow to prevent any potential instance leaks, we will definitely be dropping the Javassist dependency, but I'm afraid it may require support for interceptors that are executed before bean resolution in the interceptors spec.

**Comment by OndrejM** [comment]
Hi Jan,

Thank you for your feedback on this solution. If I can figure out how to prevent potential leaks and improve on the concept, I will let you now. Meantime, I see that the solution with Javassist is more bulletproof.

**Comment by OndrejM** [comment]
I also built some test cases based on junit, deltaspike test support and weld. Would you be interested in pull request?

**Comment by janbeernink** [comment]
Absolutely! I haven't had time to look at tests yet, so any help would be much appreciated.

**Comment by janbeernink** [comment]
We've managed to find another interceptor based approach that works without Javassist. As a result, I will close this pull request. Once again, many thanks for your interest and your pull request!

**Comment by OndrejM** [comment]
Brilliant! I'd be interested in the alternative solution. I'll check commit log. Meanwhile, I still owe you the test cases - II haven't yet enough time to finish what I've got. I was playing with DeltaSpike test tools, and later with Arquillian, so it is in a bit inconsistent state now.

**Comment by janbeernink** [comment]
The basic gist of it is that we now return "dummy" instances if no instance from the pool has been assigned to the current thread yet. We have an interceptor that detects if it's running on an instance from the pool or a dummy instance by checking if the current thread already has an allocated instance of the bean. If that isn't the case, it allocates an instance, re-resolves the bean through the BeanManager and then performs the same call again on the newly returned proxy. There are a few drawbacks to this approach, one is that we need one extra instance of the @Pooled bean for the dummy instance, but it seems to work pretty well otherwise. I hope to write up a blogpost explaining our current solution in more detail sometime this week.

**Pull request closed without merging**
